FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
# O parâmetro --host é obrigatório para acessar o Vite fora do contêiner
CMD ["npm", "run", "dev", "--", "--host"]