services:
  # O NOSSO BACK-END
  backend:
    build: ./BackEnd
    ports:
      - "3001:3001" 
    environment:
      - PORT=3001   
    restart: always

  # O NOSSO FRONT-END
  frontend:
    build: ./FrontEnd
    ports:
      - "5173:5173"
    depends_on:
      - backend     
    restart: always


# services:
#   backend:
#     build: ./BackEnd
#     expose:
#       - "3000"  
#     environment:
#       - PORT=3000
#     restart: always

#   frontend:
#     build: ./FrontEnd
#     expose:
#       - "5173"
#     tty: true
#     stdin_open: true
#     depends_on:
#       - backend
#     restart: always