version: '3.8'

services:
  backend:
    build: ./BackEnd
    ports:
      - "3000:3000"
    env_file:
      - ./BackEnd/.env
    volumes:
      - ./BackEnd:/app

  frontend:
    build: ./FrontEnd
    ports:
      - "5173:5173"
    env_file:
      - ./FrontEnd/.env
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    depends_on:
      - backend