services:

  postgres:
    image: postgres:16
    container_name: smartderm-postgres
    restart: always
    environment:
      POSTGRES_USER: smartderm
      POSTGRES_PASSWORD: smartderm123
      POSTGRES_DB: smartderm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: smartderm-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build: ./BackEnd
    container_name: smartderm-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=smartderm
      - DB_PASSWORD=smartderm123
      - DB_NAME=smartderm
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=smartderm
      - MINIO_PUBLIC_ENDPOINT=localhost
      - JWT_SECRET=smartderm_jwt_secret_2026
      - CODIGO_MEDICO=MEDICO2026
      - CODIGO_CIENTISTA=DATAADMIN2026
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEEPSEEK_API_KEY=sua_chave_aqui
      - OPENAI_API_KEY=sua_chave_aqui
      - ANTHROPIC_API_KEY=sua_chave_aqui
    depends_on:
      - postgres
      - minio

  frontend:
    build: ./FrontEnd
    container_name: smartderm-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://backend:3000
    tty: true
    stdin_open: true
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data:
