FROM node:22-slim 
WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl
COPY package*.json ./
RUN npm install
RUN npm install prisma@5 @prisma/client@5
RUN npm install multer minio bcrypt jsonwebtoken @google/generative-ai swagger swagger-ui-express
COPY . .
EXPOSE 3000
CMD sh -c "npx prisma generate && npx prisma db push && node src/server.js"